version: '3'
services:
  ui:
    build:
      context: ./frontend
    container_name: react-container
    ports:
      - '80:5173'
    command: bash -c "npm install && npm run dev --  --host"
    volumes:
      - ./frontend:/application
    environment:
      - NODE_ENV=development
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    container_name: node-container
    command: bash -c "npm install && npm run dev"
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/application    
    env_file:
      - .env